development:
  adapter: mysql
  host: 
  database: 
  username: 
  password: 
  encoding: utf8
  reconnect: true
  pool: 5
  timeout: 5000

test:
  adapter: mysql
  host: 
  database: 
  username: 
  password: 
  encoding: utf8
  reconnect: true
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  host: 
  database: 
  username: 
  password: 
  encoding: utf8
  reconnect: true
  pool: 5
  timeout: 5000
