development:
  adapter: mysql2
  host:
  database:
  username:
  password:
  encoding: utf8
  reconnect: true
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  host: 
  database: 
  username: 
  password: 
  encoding: utf8
  reconnect: true
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  host: 
  database: 
  username: 
  password: 
  encoding: utf8
  reconnect: true
  pool: 5
  timeout: 5000
